### ISSUE TITLE
OppositeColor calculation is sometimes hard to read

### ISSUE THREAD

**Issue by btastic** [MMRIZE/CX3_Shared#1]
Hello,

I was investigating why the some events are hard to read on my screen (turned up the contrast and brightness, to be fair). However, after investigating with some online accessibility checker tools, the calculation for the opposite colors leads to color combinations with a low contrast ratio.

I used this tool to check: https://webaim.org/resources/contrastchecker/

According to your code, an event-color of "#ffb100" will lead to a **white** text color (opposite color). When checking with the contrast checker, it will give you these results if white is the opposite color:

![image](https://github.com/MMRIZE/CX3_Shared/assets/6894999/6f8d09f7-a624-4935-a083-d190574fa81f)

When using a black color, the contrast is much higher, and will lead to better readability.

![image](https://github.com/MMRIZE/CX3_Shared/assets/6894999/e3560745-638c-48ff-a5f2-c6a0297231d9)

I went online for a bit and I stumbled upon this [blog post](https://24ways.org/2010/calculating-color-contrast), which has the following code snippet:

```js
function getContrastYIQ(hexcolor){
	var r = parseInt(hexcolor.substr(0,2),16);
	var g = parseInt(hexcolor.substr(2,2),16);
	var b = parseInt(hexcolor.substr(4,2),16);
	var yiq = ((r*299)+(g*587)+(b*114))/1000;
	return (yiq >= 128) ? 'black' : 'white';
}
```

Using this function in your code leads to more desirable color contrasts

**Comment by eouia** [comment]
Thanks for your contribution. I'll research and then admit your PR.

Anyway, I regard this feature as just a temporal trick. I'm waiting for a more robust and standard way `color-contrast()`.
