### ISSUE TITLE
Start Date = NaN

### ISSUE THREAD

**Issue by cestorer** [MMRIZE/CX3_Shared#3]
I'm running into an error when determining of event is today on the line "ev.today = thisMoment.toISOString().split('T')[0] === new Date(+ev.startDate).toISOString().split('T')[0]" due to startDate getting set to NaN. This is breaking MMM-CalendarExt3 :(

![image](https://github.com/MMRIZE/CX3_Shared/assets/14023142/b476f29c-5096-4574-9f10-111c503f61ac)

ev data:
```json
{
    "title": "today",
    "startDate": "2023-10-15T06:00:00.000Z",
    "endDate": "2023-10-16T04:59:59.000Z",
    "fullDayEvent": true,
    "location": false,
    "geo": false,
    "description": false,
    "today": true,
    "dayBeforeYesterday": false,
    "yesterday": false,
    "tomorrow": false,
    "dayAfterTomorrow": false,
    "symbol": [
        "fas fa-fw fa-calendar-alt"
    ],
    "calendarName": "test",
    "color": "#fff"
}
```

**Comment by eouia** [comment]
What is the event provider? default calendar module?
